services:
  forest-train:
    container_name: forest-train
    build:
      context: ./models/forest
      dockerfile: Dockerfile
    volumes:
      - ./models/forest/output:/app/output
      - ./models/forest/data:/app/data
    command:
      [
        "python",
        "src/train.py",
        "--sample=/app/data/sample.csv",
        "--output=/app/output/model.pkl",
      ]

  forest:
    container_name: forest
    build:
      context: ./models/forest
      dockerfile: Dockerfile
    # volumes:
    #   - ./models/forest/output:/app/output
    #   - ./models/forest/data:/app/data
    # environment:
    #   - SM_MODEL_DIR=/app/output
    ports:
      - "8080:8080"
