services:
  my-model-train:
    container_name: my-model-train
    build:
      context: ./models/my-model
      dockerfile: Dockerfile
    volumes:
      - ./models/my-model/output:/app/output
      - ./models/my-model/data:/app/data
    command:
      [
        "python",
        "src/train.py",
        "--sample=/app/data/sample.csv",
        "--output=/app/output",
      ]

  my-model:
    container_name: my-model
    build:
      context: ./models/my-model
      dockerfile: Dockerfile
    volumes:
      - ./models/my-model/output:/app/output
      - ./models/my-model/data:/app/data
    ports:
      - "8080:8080"
