@forest-model-endpoint=http://localhost:8080

### Run a prediction 
POST {{forest-model-endpoint}}/invocations
Content-Type: application/json

{
  "inputs": [
    [5.1, 3.5, 1.4, 0.2],
    [6.3, 3.3, 6.0, 2.5]
  ]
}

### Ping
GET {{forest-model-endpoint}}/ping
