# @forest-model-endpoint=http://localhost:8080
@forest-model-endpoint=https://runtime.sagemaker.us-east-1.amazonaws.com/endpoints/forest-model-endpoint/invocations

### Run a prediction 
POST {{forest-model-endpoint}}/
Content-Type: application/json

{
  "instances": [
    [5.1, 3.5, 1.4, 0.2],
    [6.3, 3.3, 6.0, 2.5]
  ]
}

### Health
GET {{forest-model-endpoint}}/health
