FROM python:3.11-slim

# Set environment variables
ENV PATH="/app:${PATH}"
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the code
COPY src ./src
COPY output/model.pkl ./output/model.pkl
COPY serve .
RUN chmod +x serve

# Expose
EXPOSE 8080

# Run
CMD ["serve"]

